# Compilation make for lightcurveMC/except/*
# by Krzysztof Findeisen
# Created May 2, 2013
# Last modified June 18, 2013

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     := except

SOURCES  := data.cpp inject.cpp iterator.cpp nan.cpp \
	paramlist.cpp parse.cpp r.cpp undefined.cpp 
	
include ../makefile.subdirs
include ../makefile.common
