# Compilation make for lightcurveMC/except/*
# by Krzysztof Findeisen
# Created May 2, 2013
# Last modified May 9, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = except

SOURCES  = exception.cpp \
	data.cpp fileio.cpp inject.cpp iterator.cpp nan.cpp \
	paramlist.cpp parse.cpp undefined.cpp 
	
include ../makefile.subdirs
include ../makefile.common
