# Compilation make for lightcurveMC/tests/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified April 28, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = tests

SOURCES  = testdriver.cpp test_common.cpp \
	unit_stats.cpp unit_dmdt.cpp unit_gp.cpp unit_waves.cpp

include ../makefile.subdirs
include ../makefile.common
