# Compilation make for lightcurveMC/waves/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified August 1, 2013

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     := waves

SOURCES  := multinormal.cpp stochasticrng.cpp \
	lcdeterministic.cpp lcperiodic.cpp lcstochastic.cpp lcgaussian.cpp \
	lcflat.cpp lcsine.cpp lcellipse.cpp lctriangle.cpp lcmagsine.cpp lcaatau.cpp lceclipse.cpp lcbroad.cpp \
	lcsharp.cpp lcflarepeak.cpp lcslowpeak.cpp lcsquarepeak.cpp lcflaredip.cpp \
	lcslowdip.cpp lcsquaredip.cpp \
	lcwhite.cpp lcrw.cpp lcdrw.cpp lcgp1.cpp lcgp2.cpp \
	
include ../makefile.subdirs
include ../makefile.common
