# Compilation make for lightcurveMC/waves/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified April 28, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = waves

SOURCES  = multinormal.cpp \
	lcdeterministic.cpp lcperiodic.cpp lcstochastic.cpp \
	lcflat.cpp lcsine.cpp lcellipse.cpp lctriangle.cpp lcmagsine.cpp lceclipse.cpp lcbroad.cpp \
	lcsharp.cpp lcflarepeak.cpp lcslowpeak.cpp lcsquarepeak.cpp lcflaredip.cpp \
	lcslowdip.cpp lcsquaredip.cpp \
	lcwhite.cpp lcdrw.cpp lcgp1.cpp \
	
include ../makefile.subdirs
include ../makefile.common
