# Compilation make for lightcurveMC/samples/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified April 28, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = samples

SOURCES  = observations.cpp datafactory.cpp obs_nonspitzernonvar.cpp \
	obs_spitzernonvar.cpp obs_nonspitzervar.cpp obs_spitzervar.cpp
	
include ../makefile.subdirs
include ../makefile.common
