# Compilation make for lightcurveMC/samples/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified May 9, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = samples

SOURCES  = observations.cpp datafactory.cpp
	
include ../makefile.subdirs
include ../makefile.common
