# Compilation make for lightcurveMC/cmd/*
# by Krzysztof Findeisen
# Created May 11, 2013
# Last modified May 11, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = cmd

SOURCES  = cmd.cpp cmd_classes.cpp cmd_load.cpp
	
include ../makefile.subdirs
include ../makefile.common
