# Compilation make for lightcurveMC/cmd/*
# by Krzysztof Findeisen
# Created May 11, 2013
# Last modified August 19, 2013

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     := cmd

SOURCES  := cmd.cpp cmd_classes.cpp cmd_load.cpp cmdlinedyn.cpp \
	modelparams.cpp simoptions.cpp simtype.cpp
	
include ../makefile.subdirs
include ../makefile.common
