# Compilation make for lightcurveMC/stats/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified May 18, 2013

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     := stats

SOURCES  := acfinterp.cpp dmdt.cpp experimental.cpp magdist.cpp peakfind.cpp \
	acf.cpp
	
include ../makefile.subdirs
include ../makefile.common
