# Compilation make for lightcurveMC/stats/*
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified May 7, 2013

SHELL = /bin/sh

include ../makefile.inc

#---------------------------------------
# Directory contents
PROJ     = stats

SOURCES  = dmdt.cpp magdist.cpp acfinterp.cpp experimental.cpp acf.cpp
	
include ../makefile.subdirs
include ../makefile.common
